import { Complaint } from '@/types/complaint';

export const DEMO_COMPLAINTS: Complaint[] = [
  {
    id: 'cmp-101',
    trackingNumber: 'RV-2026-9841',
    category: 'water_electricity',
    stationName: 'New Delhi Railway Station',
    stationCode: 'NDLS',
    platformNumber: 3,
    priority: 'high',
    status: 'in_progress',
    description: 'Drinking water vending cooler at the central section of Platform 3 is leaking continuously onto the tactile paving walkway, creating slipping hazards.',
    createdAt: '2026-09-12T14:20:00Z',
    updatedAt: '2026-09-13T07:45:00Z',
    hasAttachment: true,
    attachmentName: 'platform3_water_leak.jpg',
    timeline: [
      {
        id: 't-1',
        status: 'submitted',
        timestamp: '2026-09-12T14:20:00Z',
        description: 'Complaint registered via RailVision AI Assistant and logged into station maintenance queue.',
        actor: 'Passenger (You)',
      },
      {
        id: 't-2',
        status: 'under_review',
        timestamp: '2026-09-12T15:10:00Z',
        description: 'Verified by NDLS Senior Section Engineer (Works). Assigned to on-duty plumbing team.',
        actor: 'Station Controller NDLS',
      },
      {
        id: 't-3',
        status: 'in_progress',
        timestamp: '2026-09-13T07:45:00Z',
        description: 'Maintenance team on site inspecting main valve and pipe joint fitting.',
        actor: 'Sanitation & Water Maintenance Wing',
      },
    ],
  },
  {
    id: 'cmp-102',
    trackingNumber: 'RV-2026-7732',
    category: 'cleanliness',
    stationName: 'Chhatrapati Shivaji Maharaj Terminus',
    stationCode: 'CSMT',
    platformNumber: 8,
    priority: 'medium',
    status: 'resolved',
    description: 'Overflowing recycle bins near coach position S4 on Platform 8 after arrival of morning express train.',
    createdAt: '2026-09-11T09:15:00Z',
    updatedAt: '2026-09-11T11:05:00Z',
    hasAttachment: false,
    timeline: [
      {
        id: 't-4',
        status: 'submitted',
        timestamp: '2026-09-11T09:15:00Z',
        description: 'Cleanliness grievance submitted.',
        actor: 'Passenger',
      },
      {
        id: 't-5',
        status: 'in_progress',
        timestamp: '2026-09-11T09:40:00Z',
        description: 'Sanitation supervisor dispatched cleaning crew.',
        actor: 'Chief Health Inspector CSMT',
      },
      {
        id: 't-6',
        status: 'resolved',
        timestamp: '2026-09-11T11:05:00Z',
        description: 'Platform bays emptied, power washed, and inspection verified with photo signoff.',
        actor: 'Quality Assurance Cell',
      },
    ],
  },
];
