import { Facility } from '@/types/facility';

export const DEMO_FACILITIES: Facility[] = [
  {
    id: 'fac-1',
    stationId: 'ndls',
    stationCode: 'NDLS',
    name: 'IRCTC Executive Lounge & Rest Area',
    type: 'waiting_room',
    platformNear: 1,
    exactLocation: 'Platform 1, Paharganj Concourse (First Floor via Lift)',
    distanceMeters: 45,
    isOpen24Hours: true,
    operatingHours: '24/7 Service',
    isAccessible: true,
    status: 'available',
    description: 'Air-conditioned lounge with high-speed Wi-Fi, recliner seating, buffet meal options, and shower facilities.',
    contactNumber: '+91-11-23340001',
    coordinates: { x: 30, y: 18 },
  },
  {
    id: 'fac-2',
    stationId: 'ndls',
    stationCode: 'NDLS',
    name: 'State Bank of India (SBI) Multi-ATM Kiosk',
    type: 'atm',
    platformNear: 1,
    exactLocation: 'Near Main Ticket Booking Office, Exit Gate 2',
    distanceMeters: 25,
    isOpen24Hours: true,
    operatingHours: '24 Hours',
    isAccessible: true,
    status: 'available',
    description: 'Features 3 automated cash dispensers with cash deposit machine and RuPay/Visa/MasterCard support.',
    coordinates: { x: 22, y: 12 },
  },
  {
    id: 'fac-3',
    stationId: 'ndls',
    stationCode: 'NDLS',
    name: 'Jan Aahar Affordable Food Plaza',
    type: 'food',
    platformNear: 3,
    exactLocation: 'Foot-Over-Bridge 2 Landing, Platform 3-4 Island',
    distanceMeters: 90,
    isOpen24Hours: false,
    operatingHours: '05:00 AM - 11:30 PM',
    isAccessible: true,
    status: 'available',
    description: 'Hygienic subsidized thali meals, packaged rail neer, breakfast snacks, tea and coffee.',
    coordinates: { x: 55, y: 40 },
  },
  {
    id: 'fac-4',
    stationId: 'ndls',
    stationCode: 'NDLS',
    name: 'Emergency Medical Booth & First Aid Post',
    type: 'medical',
    platformNear: 16,
    exactLocation: 'Ajmeri Gate Concourse, next to Station Director Office',
    distanceMeters: 140,
    isOpen24Hours: true,
    operatingHours: '24/7 Medical Staff on duty',
    isAccessible: true,
    status: 'available',
    description: 'Equipped with basic trauma supplies, AED defibrillator, wheelchair dispatch, and on-call medical officer.',
    contactNumber: '139 (Option 4)',
    coordinates: { x: 45, y: 82 },
  },
  {
    id: 'fac-5',
    stationId: 'csmt',
    stationCode: 'CSMT',
    name: 'Divyangjan Accessibility & Wheelchair Counter',
    type: 'help_desk',
    platformNear: 8,
    exactLocation: 'Star Chamber Concourse, adjacent to Enquiry Gate',
    distanceMeters: 30,
    isOpen24Hours: true,
    operatingHours: '24 Hours Assisted Service',
    isAccessible: true,
    status: 'available',
    description: 'Free porter-assisted wheelchair mobility, battery-operated car reservations, and braille guidance maps.',
    contactNumber: '+91-22-22620173',
    coordinates: { x: 25, y: 25 },
  },
  {
    id: 'fac-6',
    stationId: 'csmt',
    stationCode: 'CSMT',
    name: 'Premium Swachh Modern Restrooms',
    type: 'toilet',
    platformNear: 14,
    exactLocation: 'Between Platforms 13 & 14, Central corridor',
    distanceMeters: 75,
    isOpen24Hours: true,
    operatingHours: '24/7 Sanitized Cleaning Cycles',
    isAccessible: true,
    status: 'available',
    description: 'Separate accessible stalls for persons with disabilities, baby care feeding room, and sensor faucets.',
    coordinates: { x: 38, y: 62 },
  },
];
