import { Station } from '@/types/station';

export const DEMO_STATIONS: Station[] = [
  {
    id: 'ndls',
    code: 'NDLS',
    name: 'New Delhi Railway Station',
    city: 'New Delhi',
    state: 'Delhi',
    zone: 'Northern Railway (NR)',
    category: 'A1',
    platformsCount: 16,
    helplineNumber: '139',
    layoutDescription: 'Double-sided terminal layout connecting Paharganj (Platform 1) and Ajmeri Gate (Platform 16) with central foot-over-bridges.',
    amenities: {
      toilets: 24,
      atms: 8,
      foodOutlets: 18,
      waitingRooms: 6,
      medicalKiosks: 2,
      wheelchairAccess: true,
    },
    platforms: [
      {
        id: 'ndls-p1',
        number: 1,
        direction: 'Northbound / Amritsar & Jammu',
        currentTrain: '12001 Shatabdi Express',
        expectedDeparture: '09:45 AM',
        isAccessible: true,
        hasElevator: true,
        hasEscalator: true,
        status: 'occupied',
        coordinates: { x: 15, y: 15 },
      },
      {
        id: 'ndls-p2',
        number: 2,
        direction: 'Central & Westbound / Mumbai & Ahmedabad',
        currentTrain: '12952 Mumbai Rajdhani',
        expectedDeparture: '16:55 PM',
        isAccessible: true,
        hasElevator: true,
        hasEscalator: true,
        status: 'active',
        coordinates: { x: 15, y: 30 },
      },
      {
        id: 'ndls-p3',
        number: 3,
        direction: 'Eastbound / Patna & Howrah',
        currentTrain: '12302 Howrah Rajdhani',
        expectedDeparture: '17:15 PM',
        isAccessible: true,
        hasElevator: false,
        hasEscalator: true,
        status: 'active',
        coordinates: { x: 15, y: 45 },
      },
      {
        id: 'ndls-p16',
        number: 16,
        direction: 'Ajmeri Gate Concourse / Airport Express Link',
        currentTrain: '22436 Vande Bharat Express',
        expectedDeparture: '06:00 AM',
        isAccessible: true,
        hasElevator: true,
        hasEscalator: true,
        status: 'active',
        coordinates: { x: 15, y: 80 },
      },
    ],
    importantPoints: [
      {
        id: 'pt-1',
        name: 'Main Paharganj Entry Gate',
        type: 'gate',
        locationDescription: 'Direct access to Platform 1 and Pre-paid Taxi stand',
        platformNear: 1,
        coordinates: { x: 5, y: 15 },
      },
      {
        id: 'pt-2',
        name: 'Ajmeri Gate Entry & Metro Link',
        type: 'gate',
        locationDescription: 'Direct connection to Delhi Metro Airport Express Line',
        platformNear: 16,
        coordinates: { x: 5, y: 80 },
      },
      {
        id: 'pt-3',
        name: 'Central Foot-Over-Bridge (FOB-2)',
        type: 'bridge',
        locationDescription: 'Ramps and elevators connecting all Platforms 1 through 16',
        platformNear: 8,
        coordinates: { x: 50, y: 50 },
      },
      {
        id: 'pt-4',
        name: 'Executive Enquiry & RITES Help Desk',
        type: 'enquiry',
        locationDescription: 'Paharganj side Ground floor concourse',
        platformNear: 1,
        coordinates: { x: 10, y: 22 },
      },
    ],
  },
  {
    id: 'csmt',
    code: 'CSMT',
    name: 'Chhatrapati Shivaji Maharaj Terminus',
    city: 'Mumbai',
    state: 'Maharashtra',
    zone: 'Central Railway (CR)',
    category: 'A1',
    platformsCount: 18,
    helplineNumber: '139',
    layoutDescription: 'Historic UNESCO heritage terminus with Platforms 1-7 for Suburban Harbour/Central and Platforms 8-18 for Long Distance trains.',
    amenities: {
      toilets: 18,
      atms: 6,
      foodOutlets: 14,
      waitingRooms: 4,
      medicalKiosks: 2,
      wheelchairAccess: true,
    },
    platforms: [
      {
        id: 'csmt-p8',
        number: 8,
        direction: 'Pune / Goa / Southbound Expresses',
        currentTrain: '12123 Deccan Queen',
        expectedDeparture: '17:10 PM',
        isAccessible: true,
        hasElevator: true,
        hasEscalator: true,
        status: 'occupied',
        coordinates: { x: 18, y: 20 },
      },
      {
        id: 'csmt-p14',
        number: 14,
        direction: 'Delhi / Northbound Terminals',
        currentTrain: '22221 Rajdhani Express',
        expectedDeparture: '16:00 PM',
        isAccessible: true,
        hasElevator: true,
        hasEscalator: true,
        status: 'active',
        coordinates: { x: 18, y: 60 },
      },
      {
        id: 'csmt-p18',
        number: 18,
        direction: 'Vande Bharat Terminus / Solapur & Shirdi',
        currentTrain: '22223 CSMT Sainagar Shirdi Vande Bharat',
        expectedDeparture: '06:20 AM',
        isAccessible: true,
        hasElevator: true,
        hasEscalator: true,
        status: 'active',
        coordinates: { x: 18, y: 85 },
      },
    ],
    importantPoints: [
      {
        id: 'csmt-pt-1',
        name: 'Heritage Concourse & Ticket Counter',
        type: 'ticket_counter',
        locationDescription: 'Main Grand Hall near Star Chamber',
        platformNear: 8,
        coordinates: { x: 8, y: 15 },
      },
      {
        id: 'csmt-pt-2',
        name: 'P. D Mello Road Outstation Entry',
        type: 'gate',
        locationDescription: 'Direct vehicular drop-off for Platforms 14-18',
        platformNear: 18,
        coordinates: { x: 8, y: 75 },
      },
    ],
  },
  {
    id: 'hwh',
    code: 'HWH',
    name: 'Howrah Junction',
    city: 'Kolkata',
    state: 'West Bengal',
    zone: 'Eastern Railway (ER)',
    category: 'A1',
    platformsCount: 23,
    helplineNumber: '139',
    layoutDescription: 'One of the largest railway complexes globally, divided into Terminal 1 (Platforms 1-15) and Terminal 2 (Platforms 16-23).',
    amenities: {
      toilets: 28,
      atms: 10,
      foodOutlets: 22,
      waitingRooms: 8,
      medicalKiosks: 3,
      wheelchairAccess: true,
    },
    platforms: [
      {
        id: 'hwh-p9',
        number: 9,
        direction: 'New Delhi / Eastern Route',
        currentTrain: '12301 Howrah Rajdhani',
        expectedDeparture: '16:50 PM',
        isAccessible: true,
        hasElevator: true,
        hasEscalator: false,
        status: 'active',
        coordinates: { x: 20, y: 35 },
      },
      {
        id: 'hwh-p22',
        number: 22,
        direction: 'South Eastern Railway / Puri & Chennai',
        currentTrain: '12841 Coromandel Express',
        expectedDeparture: '15:20 PM',
        isAccessible: true,
        hasElevator: true,
        hasEscalator: true,
        status: 'occupied',
        coordinates: { x: 20, y: 75 },
      },
    ],
    importantPoints: [
      {
        id: 'hwh-pt-1',
        name: 'Ferry Ghat & Riverside Concourse',
        type: 'gate',
        locationDescription: 'Connection to Kolkata Ferry jetty',
        platformNear: 1,
        coordinates: { x: 5, y: 10 },
      },
      {
        id: 'hwh-pt-2',
        name: 'Subway to Howrah Metro Station',
        type: 'concourse',
        locationDescription: 'Deepest metro link in India, Terminal 2 concourse',
        platformNear: 19,
        coordinates: { x: 10, y: 80 },
      },
    ],
  },
];
